### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by mathematicalmichael** [dewittpe/ucd-thesis-template#1]
where can I find these?

```
Latexmk: Missing input file: 'paralist.sty' from line
  '! LaTeX Error: File `paralist.sty' not found.'
Latexmk: Missing input file: 'xparse.sty' from line
  '! LaTeX Error: File `xparse.sty' not found.'
Latexmk: Missing input file: 'enumitem.sty' from line
  '! LaTeX Error: File `enumitem.sty' not found.'
Latexmk: Missing input file: 'ctable.sty' from line
  '! LaTeX Error: File `ctable.sty' not found.'
Latexmk: Missing input file: 'floatrow.sty' from line
  '! LaTeX Error: File `floatrow.sty' not found.'

Latexmk: Missing input file: 'subcaption.sty' from line
  '! LaTeX Error: File `subcaption.sty' not found.'
Latexmk: Missing input file: 'mathrsfs.sty' from line
  '! LaTeX Error: File `mathrsfs.sty' not found.'
Latexmk: Missing input file: 'lipsum.sty' from line
  '! LaTeX Error: File `lipsum.sty' not found.'



Latexmk: Missing input file: 'paralist.sty' from line
  '! LaTeX Error: File `paralist.sty' not found.'
Latexmk: Missing input file: 'xparse.sty' from line
  '! LaTeX Error: File `xparse.sty' not found.'
Latexmk: Missing input file: 'enumitem.sty' from line
  '! LaTeX Error: File `enumitem.sty' not found.'
Latexmk: Missing input file: 'ctable.sty' from line
  '! LaTeX Error: File `ctable.sty' not found.'
Latexmk: Missing input file: 'floatrow.sty' from line
  '! LaTeX Error: File `floatrow.sty' not found.'

Latexmk: Missing input file: 'subcaption.sty' from line
  '! LaTeX Error: File `subcaption.sty' not found.'
Latexmk: Missing input file: 'mathrsfs.sty' from line
  '! LaTeX Error: File `mathrsfs.sty' not found.'
Latexmk: Missing input file: 'lipsum.sty' from line
  '! LaTeX Error: File `lipsum.sty' not found.'


```

**Comment by dewittpe** [comment]
The missing .sty files can be obtained by extending the latex packages installed on your machine.

I work on a Debian Linux box with [TeX Live](https://www.tug.org/texlive).  The needed packages are `texlive-latex-recommended` and `texlive-latex-extra`.  Install them on your system (as root)
```
# apt install texlive-latex-recommended texlive-latex-extra
```

If you are on Windows or MacOS you'll need the equivalent packages.

**Comment by mathematicalmichael** [comment]
yeah I didn't realize the extra packages didn't come on my Ubuntu install. When I tried on my Macbook today, everything worked out of the box. THANKS SO MUCH FOR THIS. I shared it with a bunch of people in my department.

**Comment by mathematicalmichael** [comment]
I ended up building a docker image with the tex dependencies and figured out how to trick my computer into thinking it has a latex install when actually it's running within docker containers. 

All in the name of reproducibility, cross-platform (both the thesis and all my computational examples).

(In that vein, nice job with the travis file!) 

Any interest in a contribution with the Dockerfile/instructions?

**Comment by dewittpe** [comment]
Yes, I would very much like to see a docker solution.  That would be a very helpful contribution. Thanks!

**Comment by mathematicalmichael** [comment]
I tried getting it to work with docker on windows and burned 6 hours on it today (instead of writing thesis). I played with windows subsystem, got it compiling successfully, but linking it to editors and the like has proven insurmountable. I did get it running through the Ubuntu app, and more-or-less working in Command Prompt, and Powershell, which was a promising start. 

Linux. Linux for all the things. Or Mac. It does well enough. My instructions will only be for that. At the very least, it'll be a dockerized-build from command line that definitely works cross-platform (using WSL on Windows), but only seamless on Linux and Mac (I have editors thinking they're running native `latexmk` but it's actually just a bash script around `docker run` that is in my `PATH`. Windows is a total shitshow. I tried.)

**Comment by mathematicalmichael** [comment]
WIP: https://github.com/mathematicalmichael/template-thesis
(minor tweaks to make it for the math department). only thing worth checkout out right now is maybe the makefile and how it handles directories/dependencies.

**Comment by mathematicalmichael** [comment]
alright, should be ready for review. Check out `bin` and the `makefile`. Still need to do some work cleaning up the `README`... It's now as easy as `make latex_image` etc, or they can avoid building their own and pull down mine by default, using just `./docker_run.sh; ./docker_run.sh clean` to do the work (I packaged make into the docker image!).
